@startuml
title <期末考试流程>

partition 教务处 {
	start
	-->"安排考试"
	--> "考试安排表"


	===S1===--> "打印试卷"
	--> "试卷"
	"成绩单"-->if "有不及格?" then
	  -->[有] "安排补考"
	  -->===S4===
	  "安排补考"--> "补考安排表"
	  -->(*)
	endif

}
partition 教师 {
	"考试安排表"--> "出卷"
	-right-> ===S2===
    	-right-> "A、B试卷"
    	 --> ===S1===

         ===S2===-right-> "打印审批表1"

     "答卷2"-up->"阅卷出成绩"
     	-right->===S3===
         	-->"成绩单"

         ===S3===-->"答卷1"
         	-->"装订存档"
         	-->===S4===
     -->"期末流程结束"

}

partition 系主任 {
	"打印审批表1"-->"审批签字"
	-->"打印审批表2"
	--> ===S1===

}
partition 学生 {
	"试卷"-->"参加考试"
	-->"答卷2"

}



@enduml